### ISSUE TITLE
[doc] 4.1 annotated Driver Station images unclear

### ISSUE THREAD

**Issue by skeggse** [flamingchickens1540/common-chicken-runtime-engine#114]
The annotated images that lay out what the different components of the Driver Station are and what they do is hard to read: it isn't immediately clear that the green text is not part of the interface, but is instead comments.

> ![Unclear image](http://cgscomwww.catlin.edu/~skeggsc/ccre-docs/driver-station-annotated.png)

**Comment by col6y** [comment]
How would you recommend solving this?

**Comment by skeggse** [comment]
You could place the annotations to the right of the entire driver station (making the image a bit larger), and then using arrows to link specific annotations to specific controls/regions.

**Comment by col6y** [comment]
How does this look?

![driver-station-annotated](https://cloud.githubusercontent.com/assets/5056099/11315009/749e6fac-8fa0-11e5-9f04-f89a7835ffe3.png)

**Comment by skeggse** [comment]
Wayyy better!
