### ISSUE TITLE
[doc] 1.3 project rebuilding

### ISSUE THREAD

**Issue by skeggse** [flamingchickens1540/common-chicken-runtime-engine#116]
What does the documentation mean when it says the following? As someone with no experience with the framework or the common workings of robot code, it indicates to me that the project will be recompiled whenever I make a change, but I'm guessing that's not right.

> After the first time, rebuilding the project is taken care of for you.

**Comment by col6y** [comment]
Does that look better?

**Comment by skeggse** [comment]
Much better, thanks!
