### ISSUE TITLE
[doc] 1.4 eclipse toolbar layout description

### ISSUE THREAD

**Issue by skeggse** [flamingchickens1540/common-chicken-runtime-engine#117]
In the image under the following text, it isn't clear to me which button you're referring to - I can't tell at a glance what the External Tools button is (given that I haven't used eclipse for a very long time)

> Now, let’s test this code in the emulator. Open the dropdown next to the External Tools button and select "MyFirstRobot Emulate."
>
> ![Emulation description](http://cgscomwww.catlin.edu/~skeggsc/ccre-docs/emulate.png)

**Comment by col6y** [comment]
Does that work better?

**Comment by skeggse** [comment]
Perfect!
