### ISSUE TITLE
[doc] 2.0 typo in images

### ISSUE THREAD

**Issue by skeggse** [flamingchickens1540/common-chicken-runtime-engine#118]
The image under the following text has a typo: `white true` should probably be `while true`

> With traditional methods, you might think to implement that control system like this:
>
> ![Image with typo](http://cgscomwww.catlin.edu/~skeggsc/ccre-docs/pict_2.png)

as does the image following that one

> ![Second image with typo](http://cgscomwww.catlin.edu/~skeggsc/ccre-docs/pict_3.png)

**Comment by col6y** [comment]
Yup.
