### ISSUE TITLE
[doc] 2.1 clarify incorrect examples

### ISSUE THREAD

**Issue by skeggse** [flamingchickens1540/common-chicken-runtime-engine#119]
> A number of these examples aren’t the right way to do things. Keep reading.

This comment is helpful, but takes away from the entire section by not specifying which examples aren't correct. Learners can use this section to start getting a sense for what paradigms are considered correct if the individual examples are designated as the accepted/unaccepted way to do things.

**Comment by col6y** [comment]
I've individually explained the problems with some of them. Does this seem better?

**Comment by skeggse** [comment]
Much better. Would the following code even work? Seems like it would only check once - don't want to give the user the wrong idea.

```java
if (sewage_level.get() > 1000.0f) {
    // open drainage valve
}
```

**Comment by col6y** [comment]
It would work, but it would have to run in flow code, not setup code. I should probably clarify that.

**Comment by col6y** [comment]
Hmm. That help?

**Comment by skeggse** [comment]
Great!
