### ISSUE TITLE
[doc] 2.2 hardware introduction wording 

### ISSUE THREAD

**Issue by skeggse** [flamingchickens1540/common-chicken-runtime-engine#120]
Make the following more approachable:

> The CCRE contains an interface layer that lets you work with an FRC robot’s hardware with these channels.

should be something more like

> The CCRE contains an interface layer that provides access to an FRC robot's hardware via _channels_.

Also what is an interface layer in this context? The example just uses a bunch of fields/methods on `FRC`.

**Comment by col6y** [comment]
This should be better now. I've also removed the term "interface layer," but just so you know, FRC is a thin layer over an interface called FRCImplementation that is used to dispatch to different implementations based on whether the robot is real or an emulation.
