### ISSUE TITLE
[doc] 2.3 introduction of unknown variables

### ISSUE THREAD

**Issue by skeggse** [flamingchickens1540/common-chicken-runtime-engine#121]
> This connects the input to the output, so that _y_ is updated with the current value of _x_ both immediately and whenever _x_ changes. In the case of events, _send_ causes the EventOutput to be fired whenever the EventInput is produced.

What are `x` and `y`? Clarify by introducing them earlier, like so:

> The simplest example is probably _x.send(y)_, which works for all three varieties of channels:

**Comment by col6y** [comment]
I reordered the example to make more sense.
