### ISSUE TITLE
XBOX controller not attaching in emulator

### ISSUE THREAD

**Issue by tytynguyen** [flamingchickens1540/Common-Chicken-Runtime-Engine#82]
When I attempt to attach an XBOX controller in the emulator, it throws exceptions. ![Console Log](https://i.gyazo.com/7982e412fe2e550179dbf1dd55040c93.png)

Edit: I am running this on the October 1st version(8465037) of CCRE 3(Will update and try again tomorrow), 64-bit Windows 10, JDK version 1.8.0_60, with Eclipse 4.5.0.

Edit: The log from the CCRE emulator : https://gist.github.com/tytynguyen/486f9a8e81dc5b1318c5 , also added git hash.

**Comment by col6y** [comment]
Actually, xbox controllers ARE supported by the emulator; they just don't work in your case.

**Comment by col6y** [comment]
Also, please add information about your system - what OS (including version), what exact CCRE version, what version of Eclipse, and what version of the JDK.

**Comment by Others** [comment]
From the javadoc:
> ### Class NoClassDefFoundError
Thrown if the Java Virtual Machine or a ClassLoader instance tries to load in the definition of a class (as part of a normal method call or as part of creating a new instance using the new expression) and no definition of the class could be found.
The searched-for class definition existed when the currently executing class was compiled, but the definition can no longer be found.

From StackOverflow:
While it's possible that this is due to a classpath mismatch between compile-time and run-time, it's not necessarily true.

>It is important to keep two or three different exceptions straight in our head:

>1. java.lang.ClassNotFoundException This exception indicates that the class was not found on the classpath. This indicates that we were trying to load the class definition, and the class did not exist on the classpath.

>2. java.lang.NoClassDefFoundError This exception indicates that the JVM looked in its internal class definition data structure for the definition of a class and did not find it. This is different than saying that it could not be loaded from the classpath. Usually this indicates that we previously attempted to load a class from the classpath, but it failed for some reason - now we're trying to use the class again (and thus need to load it, since it failed last time), but we're not even going to try to load it, because we failed loading it earlier (and reasonably suspect that we would fail again). The earlier failure could be a ClassNotFoundException or an ExceptionInInitializerError (indicating a failure in the static initialization block) or any number of other problems. The point is, a NoClassDefFoundError is not necessarily a classpath problem.

**Comment by col6y** [comment]
Also, if possible, provide the exact CCRE git hash.

**Comment by tytynguyen** [comment]
This issue has been resolved after updating to the latest commit. However, it still doesn't allow me to attach the XBOX controller.
Log from Eclipse: ![Feed from Eclipse](https://i.gyazo.com/d872bd0412261984a40f4c569e61a6f0.png)

There is no log from the emulator.

**Comment by tytynguyen** [comment]
Well... It seems that I just needed to turn the emulator off and then back on again. It's working as intended now. Not really sure why it wouldn't work before, but I no longer have the issue!
